// <auto-generated />
namespace Fuzzyminds.ResumeAspNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class makeeduenddatenullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeeduenddatenullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201611220924392_make edu end date nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
